import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import AIBlogGenerator from "../../components/AIBlog/AIBlogGenerator";
import AIBlogCard from "../../components/AIBlog/AIBlogCard";
import "../../components/AIBlog/AIBlogGenerator.css";

/**
 * AIBlogPage — standalone page for the AI Blog Generator feature.
 * Accessible at /ai-blog. Maintains a session history of generated articles.
 */
export default function AIBlogPage() {
    const navigate = useNavigate();
    const [history, setHistory] = useState([]);

    const handleArticleGenerated = (article) => {
        setHistory((prev) => [
            { ...article, generatedAt: new Date().toISOString() },
            ...prev,
        ]);
    };

    return (
        <div className="ai-blog-page">
            <div className="ai-blog-page__container">
                {/* Back Link */}
                <button
                    className="ai-blog-page__back-link"
                    onClick={() => navigate("/blog")}
                >
                    <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                        <path
                            d="M10 12L6 8L10 4"
                            stroke="currentColor"
                            strokeWidth="1.5"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                        />
                    </svg>
                    Back to Blog
                </button>

                {/* Hero Section */}
                <motion.section
                    className="ai-blog-page__hero"
                    initial={{ opacity: 0, y: -20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6 }}
                >
                    <div className="ai-blog-page__hero-badge">
                        <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                            <path
                                d="M8 1L10.2 5.6L15 6.5L11.5 10L12.3 15L8 12.6L3.7 15L4.5 10L1 6.5L5.8 5.6L8 1Z"
                                stroke="currentColor"
                                strokeWidth="1.5"
                                strokeLinejoin="round"
                            />
                        </svg>
                        AI-Powered Content Generation
                    </div>

                    <h1 className="ai-blog-page__hero-title">
                        AI Blog Generator
                    </h1>

                    <p className="ai-blog-page__hero-subtitle">
                        Type any crypto topic and instantly get a clean, educational blog
                        post generated by AI. Perfect for learning about blockchain,
                        DeFi, staking, and more.
                    </p>
                </motion.section>

                {/* Generator Component */}
                <AIBlogGenerator onArticleGenerated={handleArticleGenerated} />

                {/* Previously Generated Articles */}
                {history.length > 1 && (
                    <motion.section
                        className="ai-blog-page__history"
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        transition={{ delay: 0.3 }}
                    >
                        <div className="ai-blog-page__history-header">
                            <h2 className="ai-blog-page__history-title">
                                Previously Generated
                            </h2>
                            <span className="ai-blog-page__history-count">
                                {history.length - 1}
                            </span>
                        </div>

                        {history.slice(1).map((article, index) => (
                            <AIBlogCard
                                key={`${article.title}-${index}`}
                                article={article}
                                onNewArticle={() => {
                                    window.scrollTo({ top: 0, behavior: "smooth" });
                                }}
                            />
                        ))}
                    </motion.section>
                )}
            </div>
        </div>
    );
}
