import React from "react";
import { motion } from "framer-motion";
import "./AIBlogCard.css";

/**
 * AIBlogCard — renders a structured AI-generated blog article
 * as a premium styled card.
 *
 * Props:
 *   article: { title, introduction, keyPoints[], summary, isDemo }
 *   onNewArticle: () => void  — callback to generate a new article
 */
export default function AIBlogCard({ article, onNewArticle }) {
    if (!article) return null;

    const { title, introduction, keyPoints, summary, isDemo } = article;
    const now = new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "short",
        day: "numeric",
    });

    return (
        <motion.div
            className="ai-blog-card"
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
        >
            {/* Header */}
            <div className="ai-blog-card__header">
                <div className="ai-blog-card__badges">
                    <span className="ai-blog-card__badge ai-blog-card__badge--ai">
                        ✨ AI Generated
                    </span>
                    {isDemo ? (
                        <span className="ai-blog-card__badge ai-blog-card__badge--demo">
                            Demo Mode
                        </span>
                    ) : (
                        <span className="ai-blog-card__badge ai-blog-card__badge--live">
                            Live AI
                        </span>
                    )}
                    <span className="ai-blog-card__timestamp">{now}</span>
                </div>
                <h2 className="ai-blog-card__title">{title}</h2>
            </div>

            {/* Body */}
            <div className="ai-blog-card__body">
                {/* Introduction */}
                <div className="ai-blog-card__intro">
                    <p>{introduction}</p>
                </div>

                {/* Key Points */}
                <div className="ai-blog-card__section-title">
                    <span className="ai-blog-card__section-icon">🔑</span>
                    Key Points
                </div>
                <div className="ai-blog-card__key-points">
                    {keyPoints?.map((point, index) => (
                        <motion.div
                            key={index}
                            className="ai-blog-card__point"
                            initial={{ opacity: 0, x: -20 }}
                            animate={{ opacity: 1, x: 0 }}
                            transition={{ delay: 0.1 * (index + 1), duration: 0.4 }}
                        >
                            <div className="ai-blog-card__point-number">
                                {String(index + 1).padStart(2, "0")}
                            </div>
                            <div className="ai-blog-card__point-content">
                                <h4>{point.heading}</h4>
                                <p>{point.text}</p>
                            </div>
                        </motion.div>
                    ))}
                </div>

                {/* Summary */}
                <div className="ai-blog-card__section-title">
                    <span className="ai-blog-card__section-icon">✅</span>
                    Summary
                </div>
                <div className="ai-blog-card__summary">
                    <p>{summary}</p>
                </div>
            </div>

            {/* Footer */}
            <div className="ai-blog-card__footer">
                <span className="ai-blog-card__footer-text">
                    {isDemo
                        ? "This is demo content. Add a Gemini API key for live AI generation."
                        : "Generated by Google Gemini AI"}
                </span>
                <button className="ai-blog-card__new-btn" onClick={onNewArticle}>
                    <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                        <path
                            d="M1 7H13M7 1V13"
                            stroke="currentColor"
                            strokeWidth="2"
                            strokeLinecap="round"
                        />
                    </svg>
                    New Article
                </button>
            </div>
        </motion.div>
    );
}
